# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  bookingapi:
    container_name: bookingapi
    image: bookingapi
    environment:
      - PORT=5000
    ports: 
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
